### ISSUE TITLE
Sichtung SLM Typen / Festlegung

### ISSUE THREAD

**Issue by Schteffen** [999Fritsch/BewerberungsAssistent#3]
Bspw zu erproben:
Llama 3.2
Phi 3
Gemma 2B

**Comment by 999Fritsch** [comment]
@Schteffen 
ChatGPT on Phi3.5 gguf models:

"If you have limited RAM and want to run the model on a CPU, the key considerations are:

    File Size: You’ll need a smaller model to fit within your available RAM.
    CPU Optimization: I-quants are optimized for performance on CPUs.
    Quality: Balance size with acceptable quality.

Recommended Model:

    Phi-3.5-mini-instruct-IQ4_XS.gguf (2.06GB)
        Why: It’s optimized for smaller size and decent quality, specifically recommended for CPU usage when RAM is limited.

Alternatives (Smaller but Lower Quality):

    Phi-3.5-mini-instruct-IQ3_M.gguf (1.86GB)
        Medium-low quality but decent for low RAM scenarios.
    Phi-3.5-mini-instruct-IQ3_XS.gguf (1.63GB)
        Slightly lower quality but very small.
    Phi-3.5-mini-instruct-IQ2_M.gguf (1.32GB)
        Very low quality but usable, if you’re very constrained.

Additional Tips:

    Use a quantized model ending with _XS or _M to prioritize low RAM usage and still maintain acceptable performance.
    Ensure you have sufficient free system RAM to load the model plus room for other processes. Aim for at least 2GB of free RAM above the model size to avoid swapping to disk, which would slow down performance drastically."
